[project]
name = "measurements"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "pyfar>=0.7.2",
    "pyroomacoustics>=0.8.3",
    "sounddevice>=0.5.1",
]
